ci: Set --nocleanup for Windows functional tests
This avoids intermittent issues in the CI Task when a test passes
successfully. For example:

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ContainerAdministrator\\AppData\\Local\\Temp\\test_runner_₿_🏃_20210920_072037\\feature_versionbits_warning_89\\alert.txt'